version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 2312
      POSTGRES_DB: 'postgres'
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      discovery.type: 'single-node'
      ELASTICSEARCH_USER: 'elastic'
      ELASTICSEARCH_PASSWORD: 'bdl6t5q-fNscEgYVe5rl'
    ports:
      - '9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  redis:
    driver: local
  esdata:
    driver: local
  db:
    driver: local
